### ISSUE TITLE
BGM music keeps playing even after app is minimised

### ISSUE THREAD

**Issue by YohanWadia** [flame-engine/flame_audio#10]
Hey after checking on discord .... it seems like this is a bug

Im working with the latest FlameAudio with flame rc5
BUT everytime I press HOME button, the BGM music keeps on playing. I have to knocked the app out via the task manager to kill the music.
It doesnt happen with the BACK button.... Only with the HOME button. 
Any idea how to solve this?

**Comment by luanpotter** [comment]
Did you initialize the `Bgm` instance you are using? That should bind it as a listener to the

```
didChangeAppLifecycleState
```

event. Can you add a println to that method to make sure it's called and if so what's the vent (ie is it an issue with Flutter events or an issue with our controlling of the audioplayer instance)?
