### ISSUE TITLE
Updating to audioplayers 0.19.0

### ISSUE THREAD

**Issue by joshkautz** [flame-engine/flame_audio#14]
I'm trying to use flame_audio to target builds to the web platform, which audioplayers v0.19.0 now supports. I want to help contribute to updating flame_audio to use audioplayers v0.19.0 dependency, but I'm encountering some issues along the lines of the `'package:audioplayers/audio_cache.dart'` file missing and _AudioPlayerState_ being undefined. I'll continue to tinker around, but would be far more happy to work alongside anyone on the team that may already have plans for supporting the web platform in the pipelines. Cheers!

**Comment by spydon** [comment]
I think you are in luck, it looks like luan has updated `flame_audio` to the newest audioplayers version very recently so he is probably going to do a release very soon:
https://github.com/flame-engine/flame/blob/main/packages/flame_audio/pubspec.yaml
Also `flame_audio` has moved in to the flame monorepo, so the code in this repo is a little bit outdated.

**Comment by joshkautz** [comment]
That's fantastic news. Thanks for the information @spydon really appreciate it! I'll try to mess around with importing it into my project.

**Comment by spydon** [comment]
> That's fantastic news. Thanks for the information @spydon really appreciate it! I'll try to mess around with importing it into my project.

It's now release as 1.0.0-rc1 :)
