### ISSUE TITLE
[BUG] audioplayers v0.17.2

### ISSUE THREAD

**Issue by augusto3691** [flame-engine/flame_audio#5]
The version of  audioplayers has a bug v0.17.2: see here: [stackOverflow](https://stackoverflow.com/questions/65540471/flutter-unable-to-build-apk-due-the-package-audioplayers)

Please downgrade to 0.16.2, this worked fine.

**Comment by idootop** [comment]
+1

**Comment by hedhyw** [comment]
+1

**Comment by luanpotter** [comment]
This has since been fixed on Ap 0.17.3+, so this PR should fix the issue: https://github.com/flame-engine/flame_audio/pull/6
