### ISSUE TITLE
Bgm.seek() and call backs???

### ISSUE THREAD

**Issue by YohanWadia** [flame-engine/flame_audio#7]
Your example is really nice. But I have used the previous verion with flame.audio to gain info from call backs and listeners.
Im finding it very hard to get that implemented with this new version.
May be you could show us how...

let me give you an idea in the old version i could do something like 
`homeBGM.seek(Duration.zero);`
or may be even something like this
`homeBGM.onPlayerCompletion.listen((event) { `

I found what i need at **FlameAudio.bgm.audioPlayer**

But im not able to do this with an **audioPlayer**.... Im able to handle regular stuff with only **bgm**:
- Get the track to load from the asset into the audioPlayer
- Make that track play from that audioPlayer
- be able to reference that audioPlayer to use stuff like... start/stop/onPlayerCompletion etc etc

Would be great if you could show us how with this new version. Once again- _**Everything works in bgm via your example. But Im not able to get the required results if i follow the same steps for audioPlayer.**_ 
Thanks

**Comment by luanpotter** [comment]
You should still be able to access the instance of audioplayers being used on Bgm via `FlameAudio.bgm.audioPlayer`, right?

So:

```dart
FlameAudio.bgm.audioPlayer?.seek(Duration(...));
```

Should work? Or am I missing something?
